name: joga11
title: My Docs
description: An example of technical documentation hosted on Github pages, using the Just the Docs Jekyll theme
remote_theme: joga11/just-the-docs

color_scheme: dark

# logo: "/assets/images/bimatrix-code.jpg"

aux_links:
  "Source repository on GitHub":
    - "//github.com/joga11/joga11.github.io"

back_to_top: true
back_to_top_text: "Back to top"

footer_content: "&copy; 2021 Joanna Gajewska"